# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 398ad3ff1d1fa13ee859f785262845ca27f9fc91ccf45fc59c6a6b51be91bfbc5da50b18024d3139633b75bbf1a06d23d749411cd33c95eee24037820841118c

test:
  secret_key_base: df50f66ff9f055aadfe966ef46a2b02eba9dff77b33861e8b0f7734016ccb9a0c1ab252959670e721e3343ce21321219acfe48b797bdcd508519b83d8020b2ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
